### ISSUE TITLE
Create an android application for Slash

### ISSUE THREAD

**Issue by anshulp2912** [rohan22shah/slash-phase3#2]
**Is your feature request related to a problem? Please describe.**
Create an android application for Slash for better usability and reach

**Comment by anshulp2912** [comment]
Create a dropdown list for selection of website

**Comment by anshulp2912** [comment]
Add logos of website beside the product

**Comment by anshulp2912** [comment]
Walmart showing sponsored item, please rectify

**Comment by darshanp228** [comment]
> Walmart showing sponsored item, please rectify

Rectified and all functionalities are working as expected
